version: 0.2
name: Build React App
on:
  push:
     branches: [ master ]

proxy:
  upload-artifacts: yes
  logs: yes

phases:
   install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
   build:
    commands:
      - npm run build
   
artifacts:
  files:
    - dist/*
  discard-paths: yes

