version: 0.2

run-as: ubuntu
 on -
   push:
     "master"
proxy:
  upload-artifacts: yes
  logs: yes

phases:

  build:
    commands:
      - npm run build
   
artifacts:
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes

