version: 0.2
name: Build React App
on:
  push:
     branches: [ master ]

run-as: ubuntu

proxy:
  upload-artifacts: yes
  logs: yes

phases:

  build:
    commands:
      - npm run build
   
artifacts:
  files:
    - dist/*
  discard-paths: yes

